//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedProyectos.ServicioAsociacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios/", ConfigurationName="ServicioAsociacion.Asociaciones")]
    public interface Asociaciones {
        
        // CODEGEN: Generating message contract since element name nombre from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/Asociaciones/crearAsociacionRequest", ReplyAction="http://servicios/Asociaciones/crearAsociacionResponse")]
        RedProyectos.ServicioAsociacion.crearAsociacionResponse crearAsociacion(RedProyectos.ServicioAsociacion.crearAsociacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class crearAsociacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="crearAsociacion", Namespace="http://servicios/", Order=0)]
        public RedProyectos.ServicioAsociacion.crearAsociacionRequestBody Body;
        
        public crearAsociacionRequest() {
        }
        
        public crearAsociacionRequest(RedProyectos.ServicioAsociacion.crearAsociacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class crearAsociacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string usuario;
        
        public crearAsociacionRequestBody() {
        }
        
        public crearAsociacionRequestBody(string nombre, string descripcion, string usuario) {
            this.nombre = nombre;
            this.descripcion = descripcion;
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class crearAsociacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="crearAsociacionResponse", Namespace="http://servicios/", Order=0)]
        public RedProyectos.ServicioAsociacion.crearAsociacionResponseBody Body;
        
        public crearAsociacionResponse() {
        }
        
        public crearAsociacionResponse(RedProyectos.ServicioAsociacion.crearAsociacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class crearAsociacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public crearAsociacionResponseBody() {
        }
        
        public crearAsociacionResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AsociacionesChannel : RedProyectos.ServicioAsociacion.Asociaciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsociacionesClient : System.ServiceModel.ClientBase<RedProyectos.ServicioAsociacion.Asociaciones>, RedProyectos.ServicioAsociacion.Asociaciones {
        
        public AsociacionesClient() {
        }
        
        public AsociacionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AsociacionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsociacionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsociacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RedProyectos.ServicioAsociacion.crearAsociacionResponse RedProyectos.ServicioAsociacion.Asociaciones.crearAsociacion(RedProyectos.ServicioAsociacion.crearAsociacionRequest request) {
            return base.Channel.crearAsociacion(request);
        }
        
        public bool crearAsociacion(string nombre, string descripcion, string usuario) {
            RedProyectos.ServicioAsociacion.crearAsociacionRequest inValue = new RedProyectos.ServicioAsociacion.crearAsociacionRequest();
            inValue.Body = new RedProyectos.ServicioAsociacion.crearAsociacionRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            inValue.Body.usuario = usuario;
            RedProyectos.ServicioAsociacion.crearAsociacionResponse retVal = ((RedProyectos.ServicioAsociacion.Asociaciones)(this)).crearAsociacion(inValue);
            return retVal.Body.@return;
        }
    }
}
