//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedProyectos.ServicioEstados {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios/", ConfigurationName="ServicioEstados.Estados")]
    public interface Estados {
        
        // CODEGEN: Generating message contract since element name descripcion from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/Estados/setComentarioRequest", ReplyAction="http://servicios/Estados/setComentarioResponse")]
        RedProyectos.ServicioEstados.setComentarioResponse setComentario(RedProyectos.ServicioEstados.setComentarioRequest request);
        
        // CODEGEN: Generating message contract since element name descripcion from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/Estados/setEstadoRequest", ReplyAction="http://servicios/Estados/setEstadoResponse")]
        RedProyectos.ServicioEstados.setEstadoResponse setEstado(RedProyectos.ServicioEstados.setEstadoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setComentarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setComentario", Namespace="http://servicios/", Order=0)]
        public RedProyectos.ServicioEstados.setComentarioRequestBody Body;
        
        public setComentarioRequest() {
        }
        
        public setComentarioRequest(RedProyectos.ServicioEstados.setComentarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class setComentarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int cod_estado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string user;
        
        public setComentarioRequestBody() {
        }
        
        public setComentarioRequestBody(string descripcion, int cod_estado, string user) {
            this.descripcion = descripcion;
            this.cod_estado = cod_estado;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setComentarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setComentarioResponse", Namespace="http://servicios/", Order=0)]
        public RedProyectos.ServicioEstados.setComentarioResponseBody Body;
        
        public setComentarioResponse() {
        }
        
        public setComentarioResponse(RedProyectos.ServicioEstados.setComentarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class setComentarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public setComentarioResponseBody() {
        }
        
        public setComentarioResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setEstadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setEstado", Namespace="http://servicios/", Order=0)]
        public RedProyectos.ServicioEstados.setEstadoRequestBody Body;
        
        public setEstadoRequest() {
        }
        
        public setEstadoRequest(RedProyectos.ServicioEstados.setEstadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class setEstadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string user;
        
        public setEstadoRequestBody() {
        }
        
        public setEstadoRequestBody(string descripcion, string user) {
            this.descripcion = descripcion;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setEstadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setEstadoResponse", Namespace="http://servicios/", Order=0)]
        public RedProyectos.ServicioEstados.setEstadoResponseBody Body;
        
        public setEstadoResponse() {
        }
        
        public setEstadoResponse(RedProyectos.ServicioEstados.setEstadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class setEstadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public setEstadoResponseBody() {
        }
        
        public setEstadoResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EstadosChannel : RedProyectos.ServicioEstados.Estados, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstadosClient : System.ServiceModel.ClientBase<RedProyectos.ServicioEstados.Estados>, RedProyectos.ServicioEstados.Estados {
        
        public EstadosClient() {
        }
        
        public EstadosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EstadosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstadosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstadosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RedProyectos.ServicioEstados.setComentarioResponse RedProyectos.ServicioEstados.Estados.setComentario(RedProyectos.ServicioEstados.setComentarioRequest request) {
            return base.Channel.setComentario(request);
        }
        
        public bool setComentario(string descripcion, int cod_estado, string user) {
            RedProyectos.ServicioEstados.setComentarioRequest inValue = new RedProyectos.ServicioEstados.setComentarioRequest();
            inValue.Body = new RedProyectos.ServicioEstados.setComentarioRequestBody();
            inValue.Body.descripcion = descripcion;
            inValue.Body.cod_estado = cod_estado;
            inValue.Body.user = user;
            RedProyectos.ServicioEstados.setComentarioResponse retVal = ((RedProyectos.ServicioEstados.Estados)(this)).setComentario(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RedProyectos.ServicioEstados.setEstadoResponse RedProyectos.ServicioEstados.Estados.setEstado(RedProyectos.ServicioEstados.setEstadoRequest request) {
            return base.Channel.setEstado(request);
        }
        
        public bool setEstado(string descripcion, string user) {
            RedProyectos.ServicioEstados.setEstadoRequest inValue = new RedProyectos.ServicioEstados.setEstadoRequest();
            inValue.Body = new RedProyectos.ServicioEstados.setEstadoRequestBody();
            inValue.Body.descripcion = descripcion;
            inValue.Body.user = user;
            RedProyectos.ServicioEstados.setEstadoResponse retVal = ((RedProyectos.ServicioEstados.Estados)(this)).setEstado(inValue);
            return retVal.Body.@return;
        }
    }
}
